apiVersion: v1
kind: Pod
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  containers:
  - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    name: nginx
    resources:
      limits:
        cpu: {{ .Values.service.spec.cpu }}
        memory: {{ .Values.service.spec.memory }}
