apiVersion: v1
kind: Pod
metadata:
  name: {{ .Chart.Name }}-{{ .Chart.Version}}
  namespace: {{ .Values.namespace }}
spec:
  containers:
  - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    name: redis
    ports:
    - containerPort: {{ .Values.service.spec.containerPort }}
      protocol: {{ .Values.service.spec.protocol }}



